workspace(name = "myorg_foo_lib")

load("@bazel_tools//tools/build_defs/repo:git.bzl", "git_repository")

grpc_version = "b94490bc74a2efc7274af70f276eb4c14c226d6f"

git_repository(
    name = "com_github_grpc_grpc",
    commit = grpc_version,
    remote = "https://github.com/grpc/grpc.git",
    shallow_since = "1580334702 -0800",
)

load("@com_github_grpc_grpc//bazel:grpc_deps.bzl", "grpc_deps")

grpc_deps()

load("@com_github_grpc_grpc//bazel:grpc_extra_deps.bzl", "grpc_extra_deps")

grpc_extra_deps()

load("@com_github_grpc_grpc//bazel:grpc_python_deps.bzl", "grpc_python_deps")

grpc_python_deps()
